apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: gitops
  newName: mauriciolucas22/gitops
  newTag: 9c6b50d0286e05e7b9253cf7bf5b6b9304dfcc0c
